### ISSUE TITLE
Estimate appropriate fees for transactions (with calibration options)

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1728]
The wallet should set a default fee for transactions based on data provided by the API that takes into account network conditions and execution characteristics. Currently, the wallet defaults to a constant fee regardless of these factors, leaving users to guess just what changes they might might have to make manually.

Presumably we'll want to enable these three levels of calibration:

1. **High**: Expensive / high value for broadcasting a transaction that will _very_ likely (>95% chance) be picked up by the next anchor block / has large time premium for user
2. **Normal** (for default in wallets, etc): Modest value for broadcasting a transaction that will likely (>60%) be picked up by the next anchor block / has moderate time premium for user
3. **Low**: Low value for broadcasting a transaction that will likely be picked up within 3-5 anchor blocks / has little to no time premium for user. 

See relevant work on the node here: https://github.com/blockstack/stacks-blockchain/issues/2836

It's not clear to me if we'll need a single value from the API that we can then adjust around independently on the client-side to provide these options, or whether the API needs to provide all three options, though I suspect the latter.

Companion issue for desktop wallet: https://github.com/blockstack/stacks-wallet/issues/923

**Comment by fbwoolf** [comment]
@timstackblock @Eshwari007 testing instructions are on the PR for this issue. Let me know if you have any questions.

**Comment by andresgalante** [comment]
This issue is ready to QA and should be the priority to merge this week.

**Comment by Eshwari007** [comment]
Found a bug related to the PR :https://github.com/hirosystems/stacks-wallet-web/issues/1944

**Comment by Eshwari007** [comment]
@fbwoolf In Mainnet,I used custom option to submit lower fee than the suggested fees from the list.
Twice,it failed indicating something went wrong and didnt let me submit the low fee in order to have a tx.
Then I tried the low fee and it failed too.
After couple minutes,used the same custom field for lower fee but increased the fee from the first use case,the tx was successful.
My findings is that if the fees are in high in the network and users enter '0.000072' and below its not allowing tx to be submitted.I tried several different numerical values and finally the value '0.000772' went thru when the lowest fee from the drop down fee selection was at 0.011716 STX.
Question here:
`Verify that setting a custom fee works above lowest estimation`-This test passes
`Verity low fee warning appear on submit of tx with custom fee set lower than lowest estimate`-This test passes but setting the custom fee lower than "LOW" fee also submits the tx succcessfully,should this be the case despite indicating the fee is too low and tx may fail?
Assume the minimal fee calculation that user can input for a successful tx via custom input varies based on the fees that are populated in the UI as per returned by the API in the network.Am I correct?

<img width="1015" alt="Screen Shot 2021-11-15 at 10 46 20 PM" src="https://user-images.githubusercontent.com/38872890/141892869-8996e527-2c01-4c44-92ce-9ef3237bedaf.png">
<img width="455" alt="Screen Shot 2021-11-15 at 10 46 52 PM" src="https://user-images.githubusercontent.com/38872890/141892873-f926d534-4b11-4178-9d6d-9afd38b87f38.png">

Just verified,all the tx is confirmed and I can see it in explorer:https://explorer.stacks.co/address/SP17YZQB1228EK9MPHQXA8GC4G3HVWZ66X7VRPMAX?chain=mainnet,despite throwing errors

**Comment by Eshwari007** [comment]
Also putting a comment here on Contract Call test from Testnet demo app which threw a different error on the UI:Value should be an integer.

**Comment by Eshwari007** [comment]
@fbwoolf `Max`button is working good now in both Mainnet and Testnet.

**Comment by Eshwari007** [comment]
<img width="391" alt="Screen Shot 2021-11-15 at 11 16 43 PM" src="https://user-images.githubusercontent.com/38872890/141910647-44dd0402-688a-460e-896e-9e8f7714081e.png">
Notice the Hiro Wallet icon and version little misaligned.

**Comment by Eshwari007** [comment]
The `Custom` selection isnt displaying 0.00 instead displaying `Standard`fee value
<img width="378" alt="Screen Shot 2021-11-15 at 11 34 36 PM" src="https://user-images.githubusercontent.com/38872890/142000955-26c4fcec-6549-4c49-a16a-3e6f10900ebb.png">

**Comment by Eshwari007** [comment]
@fbwoolf Let me know if you want me to create a separate issue for this but when I tested fee estimate on stxnft.com marketplace and tried purchasing from the collection,only `Custom` fee were displayed,`Low`,`High` and `Standard` was missing but the `Custom` displayed 0.00 STX Value.
<img width="753" alt="Screen Shot 2021-11-15 at 11 40 51 PM" src="https://user-images.githubusercontent.com/38872890/141922493-70294036-ae78-4f15-8be9-55d2fa76c54e.png">

**Comment by fbwoolf** [comment]
> @fbwoolf Let me know if you want me to create a separate issue for this but when I tested fee estimate on stxnft.com marketplace and tried purchasing from the collection,only `Custom` fee were displayed,`Low`,`High` and `Standard` was missing but the `Custom` displayed 0.00 STX Value.

No, this is expected behavior. If the endpoint doesn't return an estimation then we fallback to the custom input. This is good!

**Comment by fbwoolf** [comment]
> 
> Notice the Hiro Wallet icon and version little misaligned.

This is not related to my changes so would be a separate issue.

**Comment by fbwoolf** [comment]
> Also putting a comment here on Contract Call test from Testnet demo app which threw a different error on the UI:Value should be an integer.

I have not been able to repro this so I'm hoping it is fixed with my updates yest. I'll test again.

**Comment by fbwoolf** [comment]
> @fbwoolf In Mainnet,I used custom option to submit lower fee than the suggested fees from the list. Twice,it failed indicating something went wrong and didnt let me submit the low fee in order to have a tx. Then I tried the low fee and it failed too.

I think this might be api issues? I'll test again today.

**Comment by Eshwari007** [comment]
@fbwoolf I think this is an issue with the API,as I was reading thru some of other users experiences in the API channel,they mimic very similar to my use case while I was testing it last night. https://explorer.stacks.co/address/SP17YZQB1228EK9MPHQXA8GC4G3HVWZ66X7VRPMAX?chain=mainnet

The tx fails but then user resends another tx,end up having 5 successfully tx and having less STX in the account.Thought will bring this up to your attention.

**Comment by Eshwari007** [comment]
@fbwoolf Tested the use case when user inputs lower than the `Low` fee,the low fee warning is displayed.**This is correct behaviour.**
However,when an user increases the fee value in the custom box more than the `Low` fee,yet the warning still persist.Shouldnt the warning goes away after the fee has been increased beyond the suggested` Low` fee?attaching the video for your perusal

https://user-images.githubusercontent.com/38872890/142064681-adf90f44-3fb4-4357-9ec1-425204a868ea.mov

**Comment by Eshwari007** [comment]
@fbwoolf Also the `Custom` selection yet retains the last selected fee values in the dropdown,believe it should display 0.000000 STX when user selects `Custom` from the list,do correct me if otherwise.

**Comment by Eshwari007** [comment]
@fbwoolf Noticed that the increase fee options isnt working on a Pending tx.Attaching the video for perusal

https://user-images.githubusercontent.com/38872890/142068341-fc00a1c0-b17a-48c2-9e98-39bf0b2a1e9b.mov

This seems to be testnet specific as in mainnet it is working fine .

**Comment by fbwoolf** [comment]
> @fbwoolf Tested the use case when user inputs lower than the `Low` fee,the low fee warning is displayed.**This is correct behaviour.** However,when an user increases the fee value in the custom box more than the `Low` fee,yet the warning still persist.

This was def working at one point but there have been rebasing and other changes yet again today. I can test it again but I don't think it should hold up merging it into dev. Right now, I'm stuck on failing tests in the send form that seem to be related to changes with the send max button.

**Comment by fbwoolf** [comment]
> @fbwoolf Also the `Custom` selection yet retains the last selected fee values in the dropdown,believe it should display 0.000000 STX when user selects `Custom` from the list,do correct me if otherwise.

This is expected behavior. We can change it if there is feedback it should reset.

**Comment by fbwoolf** [comment]
> @fbwoolf Noticed that the increase fee options isnt working on a Pending tx.Attaching the video for perusal
> 
>  increase.fee.mov 
> This seems to be testnet specific as in mainnet it is working fine .

I think this might be an issue with the popup that we see occasionally, does this happen for you in full-page view? I haven't seen this and think overall the increase fee functionality does seem to be working. I'll test again.

**Comment by Eshwari007** [comment]
> > @fbwoolf Also the `Custom` selection yet retains the last selected fee values in the dropdown,believe it should display 0.000000 STX when user selects `Custom` from the list,do correct me if otherwise.
> 
> This is expected behavior. We can change it if there is feedback it should reset.

@markmhx Your thoughts on this?Thx in ad

**Comment by Eshwari007** [comment]
> > @fbwoolf Noticed that the increase fee options isnt working on a Pending tx.Attaching the video for perusal
> > increase.fee.mov
> > This seems to be testnet specific as in mainnet it is working fine .
> 
> I think this might be an issue with the popup that we see occasionally, does this happen for you in full-page view? I haven't seen this and think overall the increase fee functionality does seem to be working. I'll test again.

@fbwoolf This seems to be an issue in the popup window only,its working fine in the full page view.Tested it in Testnet.

**Comment by Eshwari007** [comment]
@fbwoolf ,Testing the new build :v2.21.0-dev.1.241.Am noticing a weird behavior in mainnet,increase fee is not showing up in full window for pending tx and also in the popup dialogue.It was working earlier in previous build

https://user-images.githubusercontent.com/38872890/142075190-06252ba8-2883-48b2-964d-07c2ddbe6598.mov


https://user-images.githubusercontent.com/38872890/142075661-a7378de0-b932-4346-bbf5-856c4634497f.mov

**Comment by fbwoolf** [comment]
> @fbwoolf ,Testing the new build :v2.21.0-dev.1.241.Am noticing a weird behavior in mainnet,increase fee is not showing up in full window for pending tx and also in the popup dialogue.It was working earlier in previous build
> 
>  mainnet.increase.fee.mov 
>  mainnet.popup.issue.increase.fee.mov

I just tested this on dev and is working just fine on my end.

![Screen Shot 2021-11-16 at 6 58 07 PM](https://user-images.githubusercontent.com/6493321/142090042-2202c0b1-cddf-4b97-97bd-e4413cdbdf76.png)

**Comment by Eshwari007** [comment]
@fbwoolf Testing v2.21.0-dev.2

**In Mainnet**
I wanted to test tx in mainnet with nonce tweak,I was able to send two tx with two diff nonce for the same max value.
<img width="632" alt="Screen Shot 2021-11-16 at 9 03 52 PM" src="https://user-images.githubusercontent.com/38872890/142096852-ca551a96-9515-4d7e-b645-a03181d31404.png">

- Though am sure one of them will fail and will be in Pending state,shouldnt the account be aware that the same Max value cant be send twice despite the different nonce.I did receive nonce conflict the first time I increased the nonce .

https://explorer.stacks.co/txid/0x9030d3cf7a76bd92fcf4c8bce47d18c69b0ff2cae4fd013e4f23f55ada3c86bd?chain=mainnet
https://explorer.stacks.co/txid/0xf56cd2198b363d1390cc922817493beae7ab95b143387b8e2e8c301a1cde68b2?chain=mainnet

- Increase tx fee is visible in mainnet full screen(still flaky in the pop up dialogue) but the 2x,5x and 10x isnt working.

https://user-images.githubusercontent.com/38872890/142102222-0920817a-c356-4d19-b01f-f00cc7689e6f.mov

**In Testnet**

- Switching between accounts is taking way too long and even received the below as I wanted to test fee between accounts
<img width="794" alt="Screen Shot 2021-11-16 at 9 46 35 PM" src="https://user-images.githubusercontent.com/38872890/142117411-f128f663-df6a-4192-9439-be544d74f278.png">
-Closing the popup dialogue and reopening landed on the previously selected account ,however when I was testing `Max`,received the below
<img width="395" alt="Screen Shot 2021-11-16 at 9 49 21 PM" src="https://user-images.githubusercontent.com/38872890/142119809-f9fe8870-4416-4cf7-835e-b8893d6adee6.png">

**Comment by markmhendrickson** [comment]
@Eshwari007 this last issue appears unrelated to fee estimates in particular? Should we either capture its own issue, or add to the related PR if it's a regression that should block that PR's merge?

**Comment by fbwoolf** [comment]
@Eshwari007 nothing being reported here is directly related to fee estimations. You receive the `Unable to calculate max spend` toast when fee estimations are loading or if none are available. That is expected behavior. The other issues reported above likely exist on main and seem unrelated to estimation changes.

**Comment by Eshwari007** [comment]
> @Eshwari007 this last issue appears unrelated to fee estimates in particular? Should we either capture its own issue, or add to the related PR if it's a regression that should block that PR's merge?

Yes,listing all my findings here so that we can move them out as separate issues or issues related to the Fee estimates accordingly.Will do the needs

**Comment by Eshwari007** [comment]
> @Eshwari007 nothing being reported here is directly related to fee estimations. You receive the `Unable to calculate max spend` toast when fee estimations are loading or if none are available. That is expected behavior. The other issues reported above likely exist on main and seem unrelated to estimation changes.

Selected `Max`too fast bfr loading of fee estimation caused it ,I suppose in your words.Will keep an eye on this use case.

**Comment by markmhendrickson** [comment]
@Eshwari007 I'd suggest creating a new issue directly if it's unrelated to the current issue or PR in question 🙏

**Comment by Eshwari007** [comment]
> @Eshwari007 I'd suggest creating a new issue directly if it's unrelated to the current issue or PR in question 🙏

@markmhx ,Yes thats the goal upon discussing with Dev and yourselfJust making sure we covered all grounds before releasing the new feature .Started created separate tickets for non PR related issues.Also @markmhx can you kindly provide your input on `Custom` value upon selection in the dropdown should be 0.000000 STX or cached from the prev selected value?Info above:https://github.com/hirosystems/stacks-wallet-web/issues/1728#issuecomment-970705733

**Comment by Eshwari007** [comment]
@fbwoolf Overall,am good with the tests conducted on this PR.Will create separate tickets for the bugs which came across during testing Fee estimate .Am doing a quick sanity test on v2.21.0-dev.3
