### ISSUE TITLE
Clicking send and then selecting Stacks leads to error (6.54.0)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5994]
I have not yet been able to reproduce this issue. Likely caused by an unknown second factor. 
Related to unreachable wallet config? 

Steps to reproduce for the user:
1. Click on the extension icon in the browser to open Leather
2. Click Send
3. Select Stacks
4. See error:

![Image](https://github.com/user-attachments/assets/167d1466-779d-430b-b0d5-d3cd1854e9e5)

Console log
![Image](https://github.com/user-attachments/assets/8cfd879c-c785-4db6-a47f-a3b1ab5a708f)

**Comment by pete-watters** [comment]
I just tested this and I cannot reproduce it either.

I can't read the error message in the screenshot fully but it looks like there could have been a problem loading the fee estimates.

If it's working for us now I guess it was an intermittent issue and should be OK for the user now

**Comment by David-Jesse** [comment]
TypeError: Cannot read properties of undefined (reading 'fee')
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:22752:66
    at Object.ti [as useMemo] (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103257:119)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:106971:48
    at useStxSendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:22750:43)
    at StxSendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:22815:7)
    at Nh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103245:137)
    at cj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103281:258)
    at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103376:88)
    at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:389)
    at Tk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:320)
    at Ik (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:180)
    at Nk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103355:88)
    at Ek (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103357:300)
    at jg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103212:105)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103351:273

Here's the error message it keeps giving

**Comment by 314159265359879** [comment]
The user reported also trying to reinstall Leather on another browser (Brave after Chrome), but the issue persisted. 

Issue related to? https://github.com/leather-io/extension/pull/5985

**Comment by kyranjamie** [comment]
I just tried this as well and couldn't replicate. Looking at the implementation, this could be poor async handling. The fee is read with the assumption it's there, and it could be that the fee hasn't loaded by the time at which user clicks send, or they're being 429'd.

**Comment by 314159265359879** [comment]
Original reporter of this issue reported this resolved.

**Comment by markmhendrickson** [comment]
Reopening since it's still outstanding (though intermittent) and getting fixed by https://github.com/leather-io/extension/pull/6125

**Comment by 314159265359879** [comment]
This issue popped up again today:

````
TypeError: Cannot read properties of undefined (reading 'fee') at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23528:58 at Object.ti [as useMemo] (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101760:119) at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:105474:48 at useStxSendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23526:43) at StxSendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23591:7) at Nh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101748:137) at cj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101784:258) at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101879:88) at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101867:389) at Tk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101867:320) at Ik (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101867:180) at Nk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101858:88) at Gk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:101855:429) at J (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:114072:203) at MessagePort.R (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/990.js:114073:128)
````

**Comment by 314159265359879** [comment]
The user is still blocked with fee error. I expect in this case a warning is thrown and default fee is set (0.003) because fee API/config file can't be reached, leave it to the discretion of the user to edit it. 

After the fix in 6.65.0, the wallet does not crash anymore. The issue is not resolved, however. 

Steps to reproduce (when GitHub config is unreachable)
1. Click send
2. Click stacks
3. (no more crash)
4. Select amount: use "send max" for convenience
5. Add address
6. See error: "unable to read current fee"

![Image](https://github.com/user-attachments/assets/942b743f-d232-4020-aee8-56274a6d9d0a)

![Image](https://github.com/user-attachments/assets/b9410a29-313c-4928-9742-3c888f3080ca)
(the other console errors are related to local restrictions, can be ignored).

![Image](https://github.com/user-attachments/assets/3be728c2-c5b4-4930-b56b-6701378d73bc)

**Comment by markmhendrickson** [comment]
@314159265359879 this PR was merged just yesterday and presumably pending release to the store, so let's confirm resolution with this last user once it's available there? https://github.com/leather-io/extension/pull/6125

**Comment by Melchizedek4ever** [comment]
Hi,
I am still getting the same error when I use the Leather extension in Brave and getting an Error:FeeTooLow when I try to use the Xverse wallet on my Android Phone. But I suspect something else is the issue, not the gas fees.

Any suggestions on what to do?

**Comment by 314159265359879** [comment]
@Melchizedek4ever we're still working on a solution here. 

as a workaround you could try using the advanced options to set a manual fee in Xverse. 
Try 0.01 STX for example. 

Best to check with Xverse support directly though if you see it persist there. This repository is only used for Leather.
